backend:
#  name: git-gateway
#  branch: master
  name: github
  repo: OlegFilonchuk/test-netlify

media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Description", name: "description", widget: "text"}
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
        label: 'Publish Date',
        name: 'date',
        widget: 'datetime',
        required: true,
      }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          required: false,
      }
      - {
        label: 'Category',
        name: 'category',
        widget: 'relation',
        collection: 'categories',
        searchFields: ['title'],
        valueField: 'title',
      }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Categories'
    name: 'categories'
    folder: 'content/categories'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - {Label: 'Title', name: 'title', widget: 'string', required: true}
